In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
AFL_comb_df=pd.read_csv('afl_comb_CLdata.csv')
AFL_RBR_df=pd.read_csv('players_round_by_round_clean.csv')
AFL_RBR_HA_df=pd.read_csv('rbr_H_A_merged.csv')

In [8]:
AFL_comb_df.describe()

,player_id,year,games_played,kicks,marks,handballs,disposals,goals,behinds,hit_outs,...,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played,decade,disposal_efficiency,debut_age,last_age,height,weight
count,25201.000000,25201.000000,25201.000000,25201.000000,25201.000000,25201.000000,25201.000000,22880.000000,22723.000000,19716.000000,...,18366.000000,25201.000000,25201.000000,19160.000000,25201.000000,25172.000000,24005.000000,24005.000000,24005.000000,24005.000000
mean,44771.217452,2010.284076,10.858022,99.545375,43.036030,68.099123,167.644498,7.183260,5.142851,21.364881,...,0.481498,3.611920,59.967140,77.826529,2005.910083,0.596300,19.170423,28.792210,187.368673,87.673287
std,826.640408,9.309888,7.803118,92.248181,39.119296,68.632620,154.100366,10.755642,6.814033,80.680411,...,0.487807,4.327661,21.110567,14.060612,9.964525,0.126584,1.580741,3.875755,7.299732,8.460864
min,43261.000000,1983.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-6.000000,0.000000,1980.000000,0.000000,16.000000,18.000000,163.000000,63.000000
25%,44051.000000,2003.000000,3.000000,21.000000,9.000000,14.000000,35.000000,1.000000,1.000000,0.000000,...,0.000000,0.400000,45.300000,72.700000,2000.000000,0.517696,18.000000,26.000000,182.000000,82.000000
50%,44823.000000,2011.000000,10.000000,68.000000,31.000000,45.000000,117.000000,3.000000,3.000000,0.000000,...,0.300000,2.300000,59.000000,80.500000,2010.000000,0.600000,19.000000,29.000000,187.000000,86.000000
75%,45528.000000,2018.000000,19.000000,162.000000,70.000000,104.000000,270.000000,9.000000,7.000000,4.000000,...,0.800000,5.200000,74.000000,86.300000,2010.000000,0.680000,20.000000,32.000000,192.000000,93.000000
max,46374.000000,2025.000000,23.000000,512.000000,226.000000,482.000000,787.000000,123.000000,84.000000,1007.000000,...,4.000000,59.000000,149.000000,100.000000,2020.000000,1.000000,29.000000,40.000000,211.000000,118.000000

In [11]:
AFL_comb_df.info()
AFL_comb_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 25201 entries, 0 to 25200
Data columns (total 69 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25201 non-null  int64
 1   year                         25201 non-null  int64
 2   team                         25201 non-null  str
 3   is_finals                    25201 non-null  bool
 4   games_played                 25201 non-null  int64
 5   kicks                        25201 non-null  float64
 6   marks                        25201 non-null  float64
 7   handballs                    25201 non-null  float64
 8   disposals                    25201 non-null  float64
 9   goals                        22880 non-null  float64
 10  behinds                      22723 non-null  float64
 11  hit_outs                     19716 non-null  float64
 12  tackles                      24808 non-null  float64
 13  rebound_50s                  21888 non-null  float64
 14  inside_50s                   22408 non-null  float64
 15  clearances                   21969 non-null  float64
 16  clangers                     22428 non-null  float64
 17  free_kicks_for               24310 non-null  float64
 18  free_kicks_against           24381 non-null  float64
 19  brownlow_votes               18471 non-null  float64
 20  contested_possessions        22007 non-null  float64
 21  uncontested_possessions      22014 non-null  float64
 22  contested_marks              20529 non-null  float64
 23  marks_inside_50              20275 non-null  float64
 24  one_percenters               21743 non-null  float64
 25  bounces                      19802 non-null  float64
 26  goal_assists                 18366 non-null  float64
 27  total_score                  25201 non-null  int64
 28  total_fantasy_points         25201 non-null  int64
 29  total_percentage_played      19160 non-null  float64
 30  avg_kicks                    25201 non-null  float64
 31  avg_marks                    25201 non-null  float64
 32  avg_handballs                25201 non-null  float64
 33  avg_disposals                25201 non-null  float64
 34  avg_goals                    22880 non-null  float64
 35  avg_behinds                  22723 non-null  float64
 36  avg_hit_outs                 19716 non-null  float64
 37  avg_tackles                  24808 non-null  float64
 38  avg_rebound_50s              21888 non-null  float64
 39  avg_inside_50s               22408 non-null  float64
 40  avg_clearances               21969 non-null  float64
 41  avg_clangers                 22428 non-null  float64
 42  avg_free_kicks_for           24310 non-null  float64
 43  avg_free_kicks_against       24381 non-null  float64
 44  avg_contested_possessions    22007 non-null  float64
 45  avg_uncontested_possessions  22014 non-null  float64
 46  avg_contested_marks          20529 non-null  float64
 47  avg_marks_inside_50          20275 non-null  float64
 48  avg_one_percenters           21743 non-null  float64
 49  avg_bounces                  19802 non-null  float64
 50  avg_goal_assists             18366 non-null  float64
 51  avg_score                    25201 non-null  float64
 52  avg_fantasy_points           25201 non-null  float64
 53  avg_percentage_played        19160 non-null  float64
 54  decade                       25201 non-null  int64
 55  disposal_efficiency          25172 non-null  float64
 56  player_name                  24005 non-null  str
 57  player_full_name             24005 non-null  str
 58  first_name                   24005 non-null  str
 59  last_name                    24005 non-null  str
 60  born_date                    24005 non-null  str
 61  debut_date                   24005 non-null  str
 62  debut_age                    24005 non-null  float64
 63  last_date                    24005 non-null  str
 64  last_age                     24005 non-null  float64
 65  height                       24005 non-null  float64
 66  weight                       24005 non-null  float64
 67  player_link                  24005 non-null  str
 68  player_teams                 24005 non-null  str
dtypes: bool(1), float64(52), int64(6), str(10)
memory usage: 17.1 MB

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,player_link,player_teams
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"['Geelong Cats', 'St Kilda Saints']"
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"['Geelong Cats', 'St Kilda Saints']"
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"['Geelong Cats', 'St Kilda Saints']"
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"['Geelong Cats', 'St Kilda Saints']"
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,Ablett,1984-05-14,2002-03-30,17.0,2020-10-24,36.0,182.0,87.0,https://afltables.com/afl/stats/players/G/Gary...,"['Geelong Cats', 'Gold Coast Suns']"

In [9]:
AFL_RBR_df.describe()

,id,year,career_game_count,jersey_num,kicks,marks,handballs,disposals,goals,behinds,...,contested_marks,marks_inside_50,one_percenters,bounces,goal_assist,percentage_of_game_played,player_id,fantasy_points,margin,round_number
count,274079.000000,274079.000000,274079.000000,274079.000000,272780.000000,266031.000000,269649.000000,268851.000000,199352.000000,192996.000000,...,183411.000000,182711.000000,213940.000000,176746.000000,170489.000000,204406.000000,274079.000000,274079.000000,274079.000000,261277.000000
mean,317619.272323,2010.140864,90.232013,20.045512,9.202599,4.078465,6.369035,15.634575,0.825108,0.606044,...,0.642017,0.713657,2.212013,0.610707,0.453478,81.061084,44786.549860,65.245232,0.164369,11.801058
std,238902.046572,9.443692,72.633610,12.657561,4.709547,2.550781,4.077101,7.081912,1.147711,0.854019,...,0.934533,1.152437,2.163786,1.218281,0.707634,14.821258,818.522157,28.109788,43.621197,6.610842
min,1.000000,1983.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,43260.000000,-10.000000,-186.000000,0.000000
25%,72920.500000,2002.000000,31.000000,9.000000,6.000000,2.000000,3.000000,10.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,77.000000,44077.000000,45.000000,-29.000000,6.000000
50%,397681.000000,2011.000000,73.000000,19.000000,9.000000,4.000000,6.000000,15.000000,0.000000,0.000000,...,0.000000,0.000000,2.000000,0.000000,0.000000,84.000000,44856.000000,64.000000,0.000000,12.000000
75%,551100.500000,2018.000000,135.000000,30.000000,12.000000,6.000000,9.000000,20.000000,1.000000,1.000000,...,1.000000,1.000000,3.000000,1.000000,1.000000,90.000000,45542.000000,84.000000,29.000000,18.000000
max,619682.000000,2025.000000,432.000000,67.000000,37.000000,24.000000,35.000000,54.000000,16.000000,11.000000,...,10.000000,14.000000,25.000000,20.000000,10.000000,100.000000,46374.000000,210.000000,186.000000,24.000000

In [13]:
AFL_RBR_df.info()
AFL_RBR_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 274079 entries, 0 to 274078
Data columns (total 36 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id                         274079 non-null  int64
 1   team                       274079 non-null  str
 2   year                       274079 non-null  int64
 3   career_game_count          274079 non-null  int64
 4   opponent                   274079 non-null  str
 5   round                      274079 non-null  str
 6   result                     274079 non-null  str
 7   jersey_num                 274079 non-null  int64
 8   kicks                      272780 non-null  float64
 9   marks                      266031 non-null  float64
 10  handballs                  269649 non-null  float64
 11  disposals                  268851 non-null  float64
 12  goals                      199352 non-null  float64
 13  behinds                    192996 non-null  float64
 14  hit_outs                   177460 non-null  float64
 15  tackles                    245402 non-null  float64
 16  rebound_50s                211232 non-null  float64
 17  inside_50s                 227514 non-null  float64
 18  clearances                 210168 non-null  float64
 19  clangers                   224122 non-null  float64
 20  free_kicks_for             220244 non-null  float64
 21  free_kicks_against         220811 non-null  float64
 22  brownlow_votes             163608 non-null  float64
 23  contested_possessions      235260 non-null  float64
 24  uncontested_possessions    236087 non-null  float64
 25  contested_marks            183411 non-null  float64
 26  marks_inside_50            182711 non-null  float64
 27  one_percenters             213940 non-null  float64
 28  bounces                    176746 non-null  float64
 29  goal_assist                170489 non-null  float64
 30  percentage_of_game_played  204406 non-null  float64
 31  player_id                  274079 non-null  int64
 32  match_date                 274079 non-null  str
 33  fantasy_points             274079 non-null  int64
 34  margin                     274079 non-null  int64
 35  round_number               261277 non-null  float64
dtypes: float64(24), int64(7), str(5)
memory usage: 87.0 MB

,id,team,year,career_game_count,opponent,round,result,jersey_num,kicks,marks,...,marks_inside_50,one_percenters,bounces,goal_assist,percentage_of_game_played,player_id,match_date,fantasy_points,margin,round_number
0,556392,Hawthorn Hawks,1994,17,Richmond Tigers,21,W,34,5.0,4.0,...,NaN,NaN,NaN,NaN,NaN,45552,1994-08-14,36,28,21.0
1,614897,Geelong Cats,2024,1,St Kilda Saints,1,W,7,5.0,NaN,...,NaN,1.0,NaN,NaN,26.0,44356,2024-03-16,23,8,1.0
2,583553,Essendon Bombers,1999,97,Adelaide Crows,10,W,6,14.0,5.0,...,NaN,3.0,NaN,NaN,NaN,45955,1999-06-04,67,48,10.0
3,590676,Western Bulldogs,1994,36,St Kilda Saints,21,W,35,12.0,10.0,...,NaN,NaN,NaN,NaN,NaN,45656,1994-08-13,81,45,21.0
4,582473,Richmond Tigers,1997,113,Melbourne Demons,10,L,41,4.0,2.0,...,NaN,NaN,NaN,NaN,NaN,45929,1997-05-31,32,-25,10.0

In [10]:
AFL_RBR_HA_df.describe()

,id,year,career_game_count,jersey_num,kicks,marks,handballs,disposals,goals,behinds,...,marks_inside_50,one_percenters,bounces,goal_assist,percentage_of_game_played,player_id,fantasy_points,margin,round_number,crowd
count,134413.000000,134413.000000,134413.000000,134413.000000,133764.000000,130506.000000,132184.000000,131785.000000,96910.000000,93908.000000,...,88371.000000,103637.000000,85527.000000,82022.000000,97650.000000,134413.000000,134413.000000,134413.000000,132314.000000,129861.000000
mean,321361.160892,2009.704166,89.820226,20.116707,9.205257,4.082104,6.309871,15.579922,0.830420,0.610140,...,0.717147,2.226994,0.627357,0.447343,81.219529,44799.846756,64.983774,0.204281,12.993138,33162.416091
std,237688.767049,9.523019,71.868877,12.606350,4.711505,2.554684,4.042985,7.057365,1.155876,0.856117,...,1.162812,2.172403,1.242109,0.705912,14.786578,816.213684,28.098455,43.264887,5.699044,16038.365653
min,3.000000,1983.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,43260.000000,-7.000000,-186.000000,0.000000,1241.000000
25%,73913.000000,2002.000000,31.000000,9.000000,6.000000,2.000000,3.000000,10.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,77.000000,44095.000000,45.000000,-28.000000,10.000000,22226.000000
50%,413169.000000,2010.000000,73.000000,19.000000,9.000000,4.000000,6.000000,15.000000,0.000000,0.000000,...,0.000000,2.000000,0.000000,0.000000,84.000000,44885.000000,64.000000,0.000000,14.000000,31470.000000
75%,549892.000000,2018.000000,134.000000,30.000000,12.000000,6.000000,8.000000,20.000000,1.000000,1.000000,...,1.000000,3.000000,1.000000,1.000000,90.000000,45552.000000,84.000000,29.000000,17.000000,40869.000000
max,619671.000000,2025.000000,429.000000,60.000000,35.000000,24.000000,30.000000,49.000000,16.000000,9.000000,...,12.000000,25.000000,20.000000,10.000000,100.000000,46371.000000,210.000000,186.000000,24.000000,100024.000000

In [21]:
AFL_RBR_HA_df.info()
AFL_RBR_HA_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 134413 entries, 0 to 134412
Data columns (total 39 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id                         134413 non-null  int64
 1   team                       134413 non-null  str
 2   year                       134413 non-null  int64
 3   career_game_count          134413 non-null  int64
 4   opponent                   134413 non-null  str
 5   round                      134413 non-null  str
 6   result                     134413 non-null  str
 7   jersey_num                 134413 non-null  int64
 8   kicks                      133764 non-null  float64
 9   marks                      130506 non-null  float64
 10  handballs                  132184 non-null  float64
 11  disposals                  131785 non-null  float64
 12  goals                      96910 non-null   float64
 13  behinds                    93908 non-null   float64
 14  hit_outs                   86204 non-null   float64
 15  tackles                    119989 non-null  float64
 16  rebound_50s                102655 non-null  float64
 17  inside_50s                 110217 non-null  float64
 18  clearances                 101874 non-null  float64
 19  clangers                   108354 non-null  float64
 20  free_kicks_for             107737 non-null  float64
 21  free_kicks_against         107853 non-null  float64
 22  brownlow_votes             79277 non-null   float64
 23  contested_possessions      113939 non-null  float64
 24  uncontested_possessions    114299 non-null  float64
 25  contested_marks            89068 non-null   float64
 26  marks_inside_50            88371 non-null   float64
 27  one_percenters             103637 non-null  float64
 28  bounces                    85527 non-null   float64
 29  goal_assist                82022 non-null   float64
 30  percentage_of_game_played  97650 non-null   float64
 31  player_id                  134413 non-null  int64
 32  match_date                 134413 non-null  str
 33  fantasy_points             134413 non-null  int64
 34  margin                     134413 non-null  int64
 35  round_number               132314 non-null  float64
 36  home_away                  134413 non-null  str
 37  venue                      134413 non-null  str
 38  crowd                      129861 non-null  float64
dtypes: float64(25), int64(7), str(7)
memory usage: 48.0 MB

,id,team,year,career_game_count,opponent,round,result,jersey_num,kicks,marks,...,goal_assist,percentage_of_game_played,player_id,match_date,fantasy_points,margin,round_number,home_away,venue,crowd
0,556392,Hawthorn Hawks,1994,17,Richmond Tigers,21,W,34,5.0,4.0,...,NaN,NaN,45552,1994-08-14,36,28,21.0,A,Melbourne Cricket Ground,52562.0
1,614897,Geelong Cats,2024,1,St Kilda Saints,1,W,7,5.0,NaN,...,NaN,26.0,44356,2024-03-16,23,8,1.0,H,GMHBA Stadium,39352.0
2,583553,Essendon Bombers,1999,97,Adelaide Crows,10,W,6,14.0,5.0,...,NaN,NaN,45955,1999-06-04,67,48,10.0,A,AAMI Stadium,39389.0
3,590676,Western Bulldogs,1994,36,St Kilda Saints,21,W,35,12.0,10.0,...,NaN,NaN,45656,1994-08-13,81,45,21.0,A,Waverley Park,14653.0
4,582473,Richmond Tigers,1997,113,Melbourne Demons,10,L,41,4.0,2.0,...,NaN,NaN,45929,1997-05-31,32,-25,10.0,H,Melbourne Cricket Ground,28879.0

In [15]:
print(AFL_RBR_df['year'].min(), AFL_RBR_df['year'].max())
print(AFL_RBR_HA_df['year'].min(), AFL_RBR_HA_df['year'].max())

1983 2025
1983 2025

In [17]:
print('Distinct matches in AFL_RBR_df (by team+match_date):', AFL_RBR_df[['team','match_date']].drop_duplicates().shape[0])
print('Distinct matches in AFL_RBR_HA_df (by team+match_date):', AFL_RBR_HA_df[['team','match_date']].drop_duplicates().shape[0])

Distinct matches in AFL_RBR_df (by team+match_date): 14700
Distinct matches in AFL_RBR_HA_df (by team+match_date): 13493

In [24]:
# pick one specific match that exists in both
sample_match = AFL_RBR_HA_df[['team','match_date']].drop_duplicates().iloc[10]
t, d = sample_match['team'], sample_match['match_date']

rbr_players = AFL_RBR_df[(AFL_RBR_df['team']==t) & (AFL_RBR_df['match_date']==d)]['player_id'].nunique()
rbr_ha_players = AFL_RBR_HA_df[(AFL_RBR_HA_df['team']==t) & (AFL_RBR_HA_df['match_date']==d)]['player_id'].nunique()

print(f'Match: {t} on {d}')
print('Players in original RBR file:', rbr_players)
print('Players in  RBR_HA file:', rbr_ha_players)

Match: Brisbane Lions on 1999-08-15
Players in original RBR file: 22
Players in  RBR_HA file: 22

In [25]:
# pick one specific match that exists in both
sample_match = AFL_RBR_HA_df[['team','match_date']].drop_duplicates().iloc[24]
t, d = sample_match['team'], sample_match['match_date']

rbr_players = AFL_RBR_df[(AFL_RBR_df['team']==t) & (AFL_RBR_df['match_date']==d)]['player_id'].nunique()
rbr_ha_players = AFL_RBR_HA_df[(AFL_RBR_HA_df['team']==t) & (AFL_RBR_HA_df['match_date']==d)]['player_id'].nunique()

print(f'Match: {t} on {d}')
print('Players in original RBR file:', rbr_players)
print('Players in  RBR_HA file:', rbr_ha_players)

Match: Western Bulldogs on 1994-09-18
Players in original RBR file: 10
Players in  RBR_HA file: 3

In [23]:
# pick one specific match that exists in both
sample_match = AFL_RBR_HA_df[['team','match_date']].drop_duplicates().iloc[19]
t, d = sample_match['team'], sample_match['match_date']

rbr_players = AFL_RBR_df[(AFL_RBR_df['team']==t) & (AFL_RBR_df['match_date']==d)]['player_id'].nunique()
rbr_ha_players = AFL_RBR_HA_df[(AFL_RBR_HA_df['team']==t) & (AFL_RBR_HA_df['match_date']==d)]['player_id'].nunique()

print(f'Match: {t} on {d}')
print('Players in original RBR file:', rbr_players)
print('Players in  RBR_HA file:', rbr_ha_players)

Match: Richmond Tigers on 1993-06-12
Players in original RBR file: 9
Players in  RBR_HA file: 2

In [26]:
# for each unique match, compute % of players retained after merge
rbr_counts = AFL_RBR_df.groupby(['team','match_date'])['player_id'].nunique().rename('rbr_players')
rbr_ha_counts = AFL_RBR_HA_df.groupby(['team','match_date'])['player_id'].nunique().rename('rbr_ha_players')

compare = rbr_counts.to_frame().join(rbr_ha_counts, how='left').reset_index()
compare['rbr_ha_players'] = compare['rbr_ha_players'].fillna(0)
compare['retention_pct'] = compare['rbr_ha_players'] / compare['rbr_players']
compare['year'] = pd.to_datetime(compare['match_date']).dt.year
compare['decade'] = (compare['year']//10)*10

print(compare.groupby('decade')['retention_pct'].mean())

decade
1980    0.516667
1990    0.527287
2000    0.507938
2010    0.465115
2020    0.477542
Name: retention_pct, dtype: float64