In [209]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print('All libraries imported')

All libraries imported

In [210]:
df1= pd.read_csv('afl_players_info_raw.csv')

df1.info()
df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2848 entries, 0 to 2847
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2848 non-null   int64
 1   player_name          2848 non-null   object
 2   player_full_name     2848 non-null   object
 3   first_name           2848 non-null   object
 4   last_name            2848 non-null   object
 5   born_date            2848 non-null   object
 6   debut_date           2848 non-null   object
 7   debut_age            2848 non-null   int64
 8   last_date            2848 non-null   object
 9   last_age             2848 non-null   int64
 10  height               2848 non-null   int64
 11  weight               2848 non-null   int64
 12  profile_pic          637 non-null    object
 13  player_link          2848 non-null   object
 14  player_common_names  75 non-null     object
 15  player_teams         2754 non-null   object
dtypes: int64(5), object(11)
memory usage: 356.1+ KB

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,profile_pic,player_link,player_common_names,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,NaN,https://afltables.com/afl/stats/players/R/Ryan...,NaN,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,NaN,https://afltables.com/afl/stats/players/G/Gary...,NaN,"{Geelong Cats,Gold Coast Suns}"
2,43276,Leek Aleer,Leek_Aleer,Leek,Aleer,2001-08-21,2022-07-30,20,2025-09-06,24,195,85,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/L/Leek...,NaN,NaN
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,NaN,https://afltables.com/afl/stats/players/N/Nath...,NaN,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,NaN,https://afltables.com/afl/stats/players/C/Cain...,NaN,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."

In [211]:
df1.describe()

                 id    debut_age     last_age       height       weight
count   2848.000000  2848.000000  2848.000000  2848.000000  2848.000000
mean   44858.623947    19.595857    25.765449   187.344803    86.012289
std      912.449281     1.824956     4.339853     7.318328     8.923524
min    43260.000000    16.000000    18.000000   163.000000     0.000000
25%    44063.750000    18.000000    22.000000   182.000000    80.000000
50%    44885.500000    19.000000    25.000000   187.000000    85.000000
75%    45662.250000    20.000000    29.000000   192.000000    92.000000
max    46374.000000    29.000000    40.000000   211.000000   118.000000

In [212]:
df1.isnull().sum()

id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

In [213]:
df1.duplicated().sum()

np.int64(5)

In [214]:
df1.columns

Index(['id', 'player_name', 'player_full_name', 'first_name', 'last_name',
       'born_date', 'debut_date', 'debut_age', 'last_date', 'last_age',
       'height', 'weight', 'profile_pic', 'player_link', 'player_common_names',
       'player_teams'],
      dtype='object')

In [215]:
df1.columns.value_counts().sum()

np.int64(16)

In [216]:
df2= pd.read_csv('afl_players_seasonal_stats_raw.csv')
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25491 entries, 0 to 25490
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25491 non-null  object
 1   year                         25491 non-null  int64
 2   team                         25491 non-null  object
 3   is_finals                    25491 non-null  bool
 4   games_played                 25491 non-null  int64
 5   kicks                        25439 non-null  float64
 6   marks                        25306 non-null  float64
 7   handballs                    25378 non-null  float64
 8   disposals                    25467 non-null  float64
 9   goals                        22954 non-null  float64
 10  behinds                      22802 non-null  float64
 11  hit_outs                     19785 non-null  float64
 12  tackles                      24980 non-null  float64
 13  rebound_50s                  21958 non-null  float64
 14  inside_50s                   22520 non-null  float64
 15  clearances                   22056 non-null  float64
 16  clangers                     22553 non-null  float64
 17  free_kicks_for               24418 non-null  float64
 18  free_kicks_against           24513 non-null  float64
 19  brownlow_votes               18494 non-null  float64
 20  contested_possessions        22155 non-null  float64
 21  uncontested_possessions      22169 non-null  float64
 22  contested_marks              20566 non-null  float64
 23  marks_inside_50              20326 non-null  float64
 24  one_percenters               21848 non-null  float64
 25  bounces                      19837 non-null  float64
 26  goal_assists                 18399 non-null  float64
 27  total_score                  25491 non-null  int64
 28  total_fantasy_points         25491 non-null  int64
 29  total_percentage_played      19245 non-null  float64
 30  avg_kicks                    25439 non-null  float64
 31  avg_marks                    25306 non-null  float64
 32  avg_handballs                25378 non-null  float64
 33  avg_disposals                25467 non-null  float64
 34  avg_goals                    22954 non-null  float64
 35  avg_behinds                  22802 non-null  float64
 36  avg_hit_outs                 19785 non-null  float64
 37  avg_tackles                  24980 non-null  float64
 38  avg_rebound_50s              21958 non-null  float64
 39  avg_inside_50s               22520 non-null  float64
 40  avg_clearances               22056 non-null  float64
 41  avg_clangers                 22553 non-null  float64
 42  avg_free_kicks_for           24418 non-null  float64
 43  avg_free_kicks_against       24513 non-null  float64
 44  avg_contested_possessions    22155 non-null  float64
 45  avg_uncontested_possessions  22169 non-null  float64
 46  avg_contested_marks          20566 non-null  float64
 47  avg_marks_inside_50          20326 non-null  float64
 48  avg_one_percenters           21848 non-null  float64
 49  avg_bounces                  19837 non-null  float64
 50  avg_goal_assists             18399 non-null  float64
 51  avg_score                    25491 non-null  float64
 52  avg_fantasy_points           25491 non-null  float64
 53  avg_percentage_played        19245 non-null  float64
dtypes: bool(1), float64(47), int64(4), object(2)
memory usage: 10.3+ MB

/tmp/ipykernel_531/2912436240.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df2= pd.read_csv('afl_players_seasonal_stats_raw.csv')

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN

In [217]:
df2.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

In [218]:
df2.duplicated().sum()

np.int64(10)

In [219]:
df2.columns

Index(['player_id', 'year', 'team', 'is_finals', 'games_played', 'kicks',
       'marks', 'handballs', 'disposals', 'goals', 'behinds', 'hit_outs',
       'tackles', 'rebound_50s', 'inside_50s', 'clearances', 'clangers',
       'free_kicks_for', 'free_kicks_against', 'brownlow_votes',
       'contested_possessions', 'uncontested_possessions', 'contested_marks',
       'marks_inside_50', 'one_percenters', 'bounces', 'goal_assists',
       'total_score', 'total_fantasy_points', 'total_percentage_played',
       'avg_kicks', 'avg_marks', 'avg_handballs', 'avg_disposals', 'avg_goals',
       'avg_behinds', 'avg_hit_outs', 'avg_tackles', 'avg_rebound_50s',
       'avg_inside_50s', 'avg_clearances', 'avg_clangers',
       'avg_free_kicks_for', 'avg_free_kicks_against',
       'avg_contested_possessions', 'avg_uncontested_possessions',
       'avg_contested_marks', 'avg_marks_inside_50', 'avg_one_percenters',
       'avg_bounces', 'avg_goal_assists', 'avg_score', 'avg_fantasy_points',
       'avg_percentage_played'],
      dtype='object')

In [220]:
df2.columns.value_counts().sum()

np.int64(54)

#Step1: Dividing the null values columns into two groups

**Group A:** columns with very low missing values "null_values<200",
Droping values from Group A

**Group B:** columns with very high missing values "null_values>200"
, Keeping the Group B same as it its

In [221]:
df2=df2.dropna(subset=['kicks', 'marks', 'handballs', 'disposals'])

In [222]:
df2.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                             0
marks                             0
handballs                         0
disposals                         0
goals                          2322
behinds                        2479
hit_outs                       5486
tackles                         393
rebound_50s                    3313
inside_50s                     2794
clearances                     3232
clangers                       2774
free_kicks_for                  891
free_kicks_against              821
brownlow_votes                 6731
contested_possessions          3195
uncontested_possessions        3188
contested_marks                4673
marks_inside_50                4928
one_percenters                 3459
bounces                        5401
goal_assists                   6837
total_score                       0
total_fantasy_points              0
total_percentage_played        6044
avg_kicks                         0
avg_marks                         0
avg_handballs                     0
avg_disposals                     0
avg_goals                      2322
avg_behinds                    2479
avg_hit_outs                   5486
avg_tackles                     393
avg_rebound_50s                3313
avg_inside_50s                 2794
avg_clearances                 3232
avg_clangers                   2774
avg_free_kicks_for              891
avg_free_kicks_against          821
avg_contested_possessions      3195
avg_uncontested_possessions    3188
avg_contested_marks            4673
avg_marks_inside_50            4928
avg_one_percenters             3459
avg_bounces                    5401
avg_goal_assists               6837
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6044
dtype: int64

In [223]:
df2.shape

(25225, 54)

In [224]:
df1=df1.dropna(subset=['player_teams'])
df1.drop(columns=['profile_pic'],inplace=True)
df1.drop(columns=['player_common_names'],inplace=True)
df1.isnull().sum()

id                  0
player_name         0
player_full_name    0
first_name          0
last_name           0
born_date           0
debut_date          0
debut_age           0
last_date           0
last_age            0
height              0
weight              0
player_link         0
player_teams        0
dtype: int64

**Here i removed two more columns which were almost empty and had no avg value count in the dataset, so droped them.**

#Step2: Changing datatypes to actual ones which match the data in dataset

In [225]:
df1['born_date']=pd.to_datetime(df1['born_date'],errors='coerce')
df1['debut_date']=pd.to_datetime(df1['debut_date'],errors='coerce')
df1['last_date']=pd.to_datetime(df1['last_date'],errors='coerce')

In [226]:
df1['born_date'].head()

0   1991-06-25
1   1984-05-14
3   1985-12-13
4   1982-03-16
5   1995-10-07
Name: born_date, dtype: datetime64[ns]

In [227]:
df1[['born_date','debut_date','last_date']].isnull().sum()

born_date     0
debut_date    0
last_date     0
dtype: int64

In [228]:
print(df1['debut_date'].min())
print(df1['debut_date'].max())
print(df1.dtypes)

1983-03-27 00:00:00
2025-08-22 00:00:00
id                           int64
player_name                 object
player_full_name            object
first_name                  object
last_name                   object
born_date           datetime64[ns]
debut_date          datetime64[ns]
debut_age                    int64
last_date           datetime64[ns]
last_age                     int64
height                       int64
weight                       int64
player_link                 object
player_teams                object
dtype: object

#Step3: moving to drop the duplicates in both datasets

In [229]:
print(df2.duplicated().sum())
print(df2.duplicated(subset=['player_id','year']).sum())

10
5765

In [230]:
df1[df1.duplicated(keep=False)]

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,player_link,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,https://afltables.com/afl/stats/players/R/Ryan...,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,https://afltables.com/afl/stats/players/G/Gary...,"{Geelong Cats,Gold Coast Suns}"
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,https://afltables.com/afl/stats/players/N/Nath...,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,https://afltables.com/afl/stats/players/C/Cain...,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."
11,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,https://afltables.com/afl/stats/players/R/Ryan...,"{Geelong Cats,St Kilda Saints}"
19,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,https://afltables.com/afl/stats/players/G/Gary...,"{Geelong Cats,Gold Coast Suns}"
27,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,https://afltables.com/afl/stats/players/N/Nath...,"{Geelong Cats,Gold Coast Suns}"
33,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,https://afltables.com/afl/stats/players/C/Cain...,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."

In [231]:
df2[df2.duplicated(subset=['player_id','year','is_finals', 'team'], keep=False)]

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN
5,43262,2003,Geelong Cats,False,22,189.0,61.0,138.0,327.0,26.0,...,8.4,7.4,0.3,0.5,1.9,1.4,0.5,8.0,68.1,93.7
6,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
7,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
8,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
9,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
10,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN
11,43262,2003,Geelong Cats,False,22,189.0,61.0,138.0,327.0,26.0,...,8.4,7.4,0.3,0.5,1.9,1.4,0.5,8.0,68.1,93.7
19642,43260,2020,Richmond Tigers,False,-13,67.0,27.0,61.0,128.0,14.0,...,4.1,6.1,0.1,0.8,0.7,0.2,0.3,6.8,43.6,79.8
19643,43260,2020,Richmond Tigers,True,-1,5.0,4.0,3.0,8.0,0.0,...,3.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,45.0,78.0
25030,43260,2021,Richmond Tigers,False,-21,122.0,53.0,100.0,222.0,18.0,...,4.9,5.9,0.2,0.4,0.8,0.4,0.6,5.7,47.4,76.4
25031,43260,2022,Richmond Tigers,False,-7,21.0,7.0,29.0,50.0,2.0,...,3.6,3.6,0.0,0.4,0.6,0.0,0.1,2.0,28.4,38.9
25032,43260,2020,Richmond Tigers,False,-13,67.0,27.0,61.0,128.0,14.0,...,4.1,6.1,0.1,0.8,0.7,0.2,0.3,6.8,43.6,79.8
25033,43260,2020,Richmond Tigers,True,-1,5.0,4.0,3.0,8.0,0.0,...,3.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,45.0,78.0
25034,43260,2021,Richmond Tigers,False,-21,122.0,53.0,100.0,222.0,18.0,...,4.9,5.9,0.2,0.4,0.8,0.4,0.6,5.7,47.4,76.4
25035,43260,2022,Richmond Tigers,False,-7,21.0,7.0,29.0,50.0,2.0,...,3.6,3.6,0.0,0.4,0.6,0.0,0.1,2.0,28.4,38.9

In [232]:
df1.drop_duplicates(inplace=True)
df2.drop_duplicates(inplace=True)

In [233]:
df1.duplicated().sum()

np.int64(0)

In [234]:
df2.duplicated().sum()

np.int64(0)

In [235]:
df1.shape

(2750, 14)

In [236]:
df2.shape

(25215, 54)

In [237]:
print((df2['games_played'] < 0).value_counts())

games_played
False    25211
True         4
Name: count, dtype: int64

In [238]:
df2.drop(df2[df2['games_played'] < 0].index, inplace=True)

In [239]:
print((df2['games_played'] < 0).value_counts())

games_played
False    25211
Name: count, dtype: int64

In [240]:
print((df2['goals'] < 0).sum())

0

In [241]:
df2.isnull().sum().sort_values(ascending=False)

avg_goal_assists               6837
goal_assists                   6837
brownlow_votes                 6731
avg_percentage_played          6043
total_percentage_played        6043
hit_outs                       5486
avg_hit_outs                   5486
avg_bounces                    5401
bounces                        5401
marks_inside_50                4928
avg_marks_inside_50            4928
contested_marks                4673
avg_contested_marks            4673
avg_one_percenters             3459
one_percenters                 3459
rebound_50s                    3313
avg_rebound_50s                3313
avg_clearances                 3232
clearances                     3232
avg_contested_possessions      3195
contested_possessions          3195
uncontested_possessions        3188
avg_uncontested_possessions    3188
avg_inside_50s                 2794
inside_50s                     2794
avg_clangers                   2774
clangers                       2774
behinds                        2479
avg_behinds                    2479
avg_goals                      2322
goals                          2322
avg_free_kicks_for              891
free_kicks_for                  891
free_kicks_against              821
avg_free_kicks_against          821
tackles                         393
avg_tackles                     393
player_id                         0
marks                             0
disposals                         0
handballs                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                             0
avg_kicks                         0
avg_marks                         0
avg_handballs                     0
avg_disposals                     0
total_score                       0
total_fantasy_points              0
avg_score                         0
avg_fantasy_points                0
dtype: int64

In [242]:
df1 = df1.rename(columns={'id': 'player_id'})

In [243]:
df1.head()

,player_id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,player_link,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,https://afltables.com/afl/stats/players/R/Ryan...,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,https://afltables.com/afl/stats/players/G/Gary...,"{Geelong Cats,Gold Coast Suns}"
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,https://afltables.com/afl/stats/players/N/Nath...,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,https://afltables.com/afl/stats/players/C/Cain...,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."
5,43266,Blake Acres,Blake_Acres,Blake,Acres,1995-10-07,2014-05-02,18,2025-08-20,29,191,90,https://afltables.com/afl/stats/players/B/Blak...,"{Carlton Blues,Fremantle Dockers,St Kilda Saints}"

In [244]:
df1.loc[df1['weight'] == 0, 'weight'] = np.nan
print(df1['weight'].isnull().sum())

2

Filling missing weight values with the column mean, since only a small number of entries were affected (originally 0 values treated as missing) and the mean gives a reasonable estimate without discarding otherwise-valid player rows.

In [245]:
df1['weight']=df1['weight'].fillna(df1['weight'].mean())
print(df1['weight'].isnull().sum())

0

In [246]:
df1['player_teams'] = df1['player_teams'].astype(str).str.strip('{}')

In [247]:
df1['player_teams'] = df1['player_teams'].str.split(',')

In [248]:
df1['player_teams']

0                         [Geelong Cats, St Kilda Saints]
1                         [Geelong Cats, Gold Coast Suns]
3                         [Geelong Cats, Gold Coast Suns]
4       [Carlton Blues, Port Adelaide Power, St Kilda ...
5       [Carlton Blues, Fremantle Dockers, St Kilda Sa...
                              ...
2842                                     [Brisbane Lions]
2843                                      [Carlton Blues]
2844                    [Brisbane Lions, St Kilda Saints]
2845             [Fremantle Dockers, Port Adelaide Power]
2846                                   [Essendon Bombers]
Name: player_teams, Length: 2750, dtype: object

In [249]:
df2['team'] = df2['team'].str.strip().str.title()

In [250]:
df2['team']

0                         Geelong Cats
1                         Geelong Cats
2                         Geelong Cats
3                      St Kilda Saints
4                         Geelong Cats
                     ...
25486    Greater Western Sydney Giants
25487                    Carlton Blues
25488                 Melbourne Demons
25489                Fremantle Dockers
25490                    Carlton Blues
Name: team, Length: 25211, dtype: object

In [251]:
df2['decade'] = (df2['year'] // 10) * 10

In [252]:
df2['disposal_efficiency'] = df2['kicks'] / df2['disposals']

In [253]:
df2[['year','decade','kicks','disposals','disposal_efficiency']].head()

   year  decade  kicks  disposals  disposal_efficiency
0  2018    2010   17.0       38.0             0.447368
1  2018    2010    3.0        5.0             0.600000
2  2019    2010    5.0       11.0             0.454545
3  2020    2020    2.0        3.0             0.666667
4  2002    2000   37.0      100.0             0.370000

## Pre-Merge Data Quality Checks

Before combining the datasets, let's re-verify the cleanliness of `df1` and `df2`.

### Check for Missing Values in `df1` and `df2`

In [254]:
print('Missing values in df1:')
display(df1.isnull().sum())

print('\nMissing values in df2 (top 10 by count):')
display(df2.isnull().sum().sort_values(ascending=False).head(10))

Missing values in df1:

player_id           0
player_name         0
player_full_name    0
first_name          0
last_name           0
born_date           0
debut_date          0
debut_age           0
last_date           0
last_age            0
height              0
weight              0
player_link         0
player_teams        0
dtype: int64

Missing values in df2 (top 10 by count):

avg_goal_assists           6837
goal_assists               6837
brownlow_votes             6731
avg_percentage_played      6043
total_percentage_played    6043
hit_outs                   5486
avg_hit_outs               5486
avg_bounces                5401
bounces                    5401
avg_marks_inside_50        4928
dtype: int64

### Check for Duplicates in `df1` and `df2`

In [255]:
print('Duplicates in df1:', df1.duplicated(subset=['player_id']).sum())
print('Duplicates in df2:', df2.duplicated().sum())

Duplicates in df1: 0
Duplicates in df2: 0

### Check Data Types, especially for the 'player_id' column

It's crucial that the `player_id` column has a consistent data type in both DataFrames for a successful merge. We previously saw a `DtypeWarning` for `df2['player_id']`, so let's convert it to numeric.

In [256]:
# Convert 'player_id' in df2 to numeric, coercing errors to NaN
df2['player_id'] = pd.to_numeric(df2['player_id'], errors='coerce')

# Drop rows where 'player_id' became NaN after coercion (if any invalid entries existed)
df2.dropna(subset=['player_id'], inplace=True)

# Convert 'player_id' to integer type in both dataframes
df1['player_id'] = df1['player_id'].astype(int)
df2['player_id'] = df2['player_id'].astype(int)

print('Data types for df1:')
display(df1.dtypes)

print('\nData types for df2:')
display(df2.dtypes)

Data types for df1:

player_id                    int64
player_name                 object
player_full_name            object
first_name                  object
last_name                   object
born_date           datetime64[ns]
debut_date          datetime64[ns]
debut_age                    int64
last_date           datetime64[ns]
last_age                     int64
height                       int64
weight                     float64
player_link                 object
player_teams                object
dtype: object

Data types for df2:

player_id                        int64
year                             int64
team                            object
is_finals                         bool
games_played                     int64
kicks                          float64
marks                          float64
handballs                      float64
disposals                      float64
goals                          float64
behinds                        float64
hit_outs                       float64
tackles                        float64
rebound_50s                    float64
inside_50s                     float64
clearances                     float64
clangers                       float64
free_kicks_for                 float64
free_kicks_against             float64
brownlow_votes                 float64
contested_possessions          float64
uncontested_possessions        float64
contested_marks                float64
marks_inside_50                float64
one_percenters                 float64
bounces                        float64
goal_assists                   float64
total_score                      int64
total_fantasy_points             int64
total_percentage_played        float64
avg_kicks                      float64
avg_marks                      float64
avg_handballs                  float64
avg_disposals                  float64
avg_goals                      float64
avg_behinds                    float64
avg_hit_outs                   float64
avg_tackles                    float64
avg_rebound_50s                float64
avg_inside_50s                 float64
avg_clearances                 float64
avg_clangers                   float64
avg_free_kicks_for             float64
avg_free_kicks_against         float64
avg_contested_possessions      float64
avg_uncontested_possessions    float64
avg_contested_marks            float64
avg_marks_inside_50            float64
avg_one_percenters             float64
avg_bounces                    float64
avg_goal_assists               float64
avg_score                      float64
avg_fantasy_points             float64
avg_percentage_played          float64
decade                           int64
disposal_efficiency            float64
dtype: object

### Verify 'weight' column in `df1`

We previously handled zero values in the 'weight' column. Let's ensure it's free of invalid values and its statistics look reasonable.

In [257]:
print('Description of weight column in df1 after cleaning:')
display(df1['weight'].describe())

Description of weight column in df1 after cleaning:

count    2750.000000
mean       86.085517
std         8.629071
min        63.000000
25%        80.000000
50%        85.000000
75%        92.000000
max       118.000000
Name: weight, dtype: float64

### Verify 'games_played' column in `df2`

We removed negative `games_played` values. Let's ensure there are no more and its statistics are sound.

In [258]:
print('Description of games_played column in df2 after cleaning:')
display(df2['games_played'].describe())

Description of games_played column in df2 after cleaning:

count    25201.000000
mean        10.858022
std          7.803118
min          1.000000
25%          3.000000
50%         10.000000
75%         19.000000
max         23.000000
Name: games_played, dtype: float64

## Handling Missing Values in `df2`\n\nLet's calculate the percentage of missing values for each column in `df2` to decide which columns to keep.

In [259]:
missing_percentages = (df2.isnull().sum() / len(df2)) * 100
missing_summary = pd.DataFrame({'Missing %': missing_percentages})
display(missing_summary.sort_values(by='Missing %', ascending=False).head(15))

                         Missing %
avg_goal_assists         27.121940
goal_assists             27.121940
brownlow_votes           26.705289
avg_percentage_played    23.971271
total_percentage_played  23.971271
hit_outs                 21.765009
avg_hit_outs             21.765009
avg_bounces              21.423753
bounces                  21.423753
avg_marks_inside_50      19.546843
marks_inside_50          19.546843
contested_marks          18.538947
avg_contested_marks      18.538947
one_percenters           13.721678
avg_one_percenters       13.721678

## Combining the Datasets

I will now perform a `left join` to merge the seasonal statistics (`df2`) with the player background information (`df1`).

In [260]:
combined_df = df2.merge(df1, on='player_id', how='left')

print(f'Shape of combined dataset: {combined_df.shape}')
display(combined_df.head())

Shape of combined dataset: (25201, 69)

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,player_link,player_teams
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"[Geelong Cats, St Kilda Saints]"
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"[Geelong Cats, St Kilda Saints]"
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"[Geelong Cats, St Kilda Saints]"
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,Abbott,1991-06-25,2018-08-02,27.0,2020-09-05,29.0,200.0,100.0,https://afltables.com/afl/stats/players/R/Ryan...,"[Geelong Cats, St Kilda Saints]"
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,Ablett,1984-05-14,2002-03-30,17.0,2020-10-24,36.0,182.0,87.0,https://afltables.com/afl/stats/players/G/Gary...,"[Geelong Cats, Gold Coast Suns]"

In [261]:
summary_table = combined_df.groupby(['team', 'decade']).agg({
    'kicks': 'mean',
    'disposal_efficiency': 'mean',
    'games_played': 'sum'
})
display(summary_table)

                              kicks  disposal_efficiency  games_played
team             decade
Adelaide Crows   1990    107.017467             0.641668          2785
                 2000     86.272897             0.590670          5268
                 2010    110.686534             0.580205          5152
                 2020    107.824701             0.592822          3031
Brisbane Bears   1980     90.500000             0.673464            51
...                             ...                  ...           ...
Western Bulldogs 1980     71.200000             0.647569            84
                 1990     99.801527             0.638783          2772
                 2000    106.969340             0.581412          5049
                 2010     99.484277             0.551153          5067
                 2020     88.323077             0.582265          3134

[84 rows x 3 columns]

This summary shows how each team's average kicks and disposal efficiency have changed across decades, along with total games played by team per era

In [262]:
combined_df[combined_df['player_name'].isnull()]['player_id'].nunique()

358

In [263]:
stats_ids = set(combined_df[combined_df['player_name'].isnull()]['player_id'].unique())
display(stats_ids)
# compare against your original info file's player_id (renamed from 'id') set, if you still have it loaded separately

{np.int64(43276),
 np.int64(43280),
 np.int64(43292),
 np.int64(43299),
 np.int64(43307),
 np.int64(43319),
 np.int64(43325),
 np.int64(43329),
 np.int64(43332),
 np.int64(43338),
 np.int64(43348),
 np.int64(43359),
 np.int64(43361),
 np.int64(43363),
 np.int64(43364),
 np.int64(43365),
 np.int64(43369),
 np.int64(43378),
 np.int64(43379),
 np.int64(43396),
 np.int64(43400),
 np.int64(43410),
 np.int64(43420),
 np.int64(43426),
 np.int64(43431),
 np.int64(43433),
 np.int64(43440),
 np.int64(43462),
 np.int64(43472),
 np.int64(43478),
 np.int64(43493),
 np.int64(43503),
 np.int64(43511),
 np.int64(43524),
 np.int64(43533),
 np.int64(43546),
 np.int64(43547),
 np.int64(43552),
 np.int64(43555),
 np.int64(43568),
 np.int64(43571),
 np.int64(43572),
 np.int64(43574),
 np.int64(43575),
 np.int64(43583),
 np.int64(43586),
 np.int64(43587),
 np.int64(43588),
 np.int64(43594),
 np.int64(43600),
 np.int64(43607),
 np.int64(43616),
 np.int64(43617),
 np.int64(43626),
 np.int64(43644),
 np.int64(43648),
 np.int64(43650),
 np.int64(43670),
 np.int64(43671),
 np.int64(43679),
 np.int64(43688),
 np.int64(43697),
 np.int64(43705),
 np.int64(43710),
 np.int64(43715),
 np.int64(43726),
 np.int64(43729),
 np.int64(43737),
 np.int64(43741),
 np.int64(43757),
 np.int64(43768),
 np.int64(43770),
 np.int64(43772),
 np.int64(43774),
 np.int64(43775),
 np.int64(43777),
 np.int64(43780),
 np.int64(43802),
 np.int64(43803),
 np.int64(43812),
 np.int64(43815),
 np.int64(43824),
 np.int64(43826),
 np.int64(43830),
 np.int64(43834),
 np.int64(43837),
 np.int64(43841),
 np.int64(43852),
 np.int64(43865),
 np.int64(43873),
 np.int64(43880),
 np.int64(43896),
 np.int64(43901),
 np.int64(43905),
 np.int64(43912),
 np.int64(43915),
 np.int64(43927),
 np.int64(43930),
 np.int64(43949),
 np.int64(43958),
 np.int64(43966),
 np.int64(43967),
 np.int64(43968),
 np.int64(43970),
 np.int64(43989),
 np.int64(43999),
 np.int64(44005),
 np.int64(44020),
 np.int64(44021),
 np.int64(44023),
 np.int64(44034),
 np.int64(44038),
 np.int64(44040),
 np.int64(44043),
 np.int64(44047),
 np.int64(44051),
 np.int64(44052),
 np.int64(44057),
 np.int64(44061),
 np.int64(44082),
 np.int64(44085),
 np.int64(44091),
 np.int64(44101),
 np.int64(44106),
 np.int64(44108),
 np.int64(44113),
 np.int64(44117),
 np.int64(44126),
 np.int64(44131),
 np.int64(44141),
 np.int64(44144),
 np.int64(44162),
 np.int64(44167),
 np.int64(44168),
 np.int64(44170),
 np.int64(44175),
 np.int64(44179),
 np.int64(44182),
 np.int64(44200),
 np.int64(44205),
 np.int64(44206),
 np.int64(44212),
 np.int64(44222),
 np.int64(44229),
 np.int64(44236),
 np.int64(44237),
 np.int64(44247),
 np.int64(44253),
 np.int64(44259),
 np.int64(44268),
 np.int64(44269),
 np.int64(44270),
 np.int64(44282),
 np.int64(44287),
 np.int64(44296),
 np.int64(44299),
 np.int64(44311),
 np.int64(44314),
 np.int64(44317),
 np.int64(44321),
 np.int64(44324),
 np.int64(44326),
 np.int64(44327),
 np.int64(44330),
 np.int64(44350),
 np.int64(44359),
 np.int64(44361),
 np.int64(44363),
 np.int64(44376),
 np.int64(44388),
 np.int64(44390),
 np.int64(44392),
 np.int64(44396),
 np.int64(44399),
 np.int64(44402),
 np.int64(44403),
 np.int64(44423),
 np.int64(44424),
 np.int64(44435),
 np.int64(44454),
 np.int64(44467),
 np.int64(44483),
 np.int64(44484),
 np.int64(44485),
 np.int64(44507),
 np.int64(44512),
 np.int64(44516),
 np.int64(44527),
 np.int64(44539),
 np.int64(44545),
 np.int64(44546),
 np.int64(44547),
 np.int64(44549),
 np.int64(44550),
 np.int64(44565),
 np.int64(44568),
 np.int64(44578),
 np.int64(44587),
 np.int64(44597),
 np.int64(44601),
 np.int64(44602),
 np.int64(44605),
 np.int64(44606),
 np.int64(44609),
 np.int64(44618),
 np.int64(44626),
 np.int64(44636),
 np.int64(44640),
 np.int64(44645),
 np.int64(44656),
 np.int64(44657),
 np.int64(44671),
 np.int64(44675),
 np.int64(44677),
 np.int64(44679),
 np.int64(44680),
 np.int64(44692),
 np.int64(44698),
 np.int64(44702),
 np.int64(44705),
 np.int64(44720),
 np.int64(44729),
 np.int64(44733),
 np.int64(44736),
 np.int64(44750),
 np.int64(44762),
 np.int64(44764),
 np.int64(44771),
 np.int64(44774),
 np.int64(44775),
 np.int64(44776),
 np.int64(44795),
 np.int64(44797),
 np.int64(44805),
 np.int64(44810),
 np.int64(44816),
 np.int64(44822),
 np.int64(44826),
 np.int64(44842),
 np.int64(44843),
 np.int64(44848),
 np.int64(44857),
 np.int64(44859),
 np.int64(44861),
 np.int64(44874),
 np.int64(44880),
 np.int64(44881),
 np.int64(44882),
 np.int64(44888),
 np.int64(44900),
 np.int64(44907),
 np.int64(44919),
 np.int64(44925),
 np.int64(44929),
 np.int64(44933),
 np.int64(44939),
 np.int64(44950),
 np.int64(44954),
 np.int64(44957),
 np.int64(44963),
 np.int64(44967),
 np.int64(44972),
 np.int64(44981),
 np.int64(44983),
 np.int64(44989),
 np.int64(44999),
 np.int64(45009),
 np.int64(45011),
 np.int64(45012),
 np.int64(45035),
 np.int64(45040),
 np.int64(45043),
 np.int64(45050),
 np.int64(45063),
 np.int64(45070),
 np.int64(45074),
 np.int64(45075),
 np.int64(45084),
 np.int64(45091),
 np.int64(45093),
 np.int64(45096),
 np.int64(45104),
 np.int64(45105),
 np.int64(45129),
 np.int64(45130),
 np.int64(45134),
 np.int64(45135),
 np.int64(45136),
 np.int64(45165),
 np.int64(45166),
 np.int64(45167),
 np.int64(45168),
 np.int64(45173),
 np.int64(45174),
 np.int64(45178),
 np.int64(45184),
 np.int64(45185),
 np.int64(45190),
 np.int64(45194),
 np.int64(45198),
 np.int64(45202),
 np.int64(45203),
 np.int64(45210),
 np.int64(45215),
 np.int64(45225),
 np.int64(45229),
 np.int64(45231),
 np.int64(45232),
 np.int64(45243),
 np.int64(45244),
 np.int64(45247),
 np.int64(45250),
 np.int64(45252),
 np.int64(45253),
 np.int64(45260),
 np.int64(45269),
 np.int64(45276),
 np.int64(45287),
 np.int64(45290),
 np.int64(45291),
 np.int64(45292),
 np.int64(45299),
 np.int64(45300),
 np.int64(45303),
 np.int64(45322),
 np.int64(45353),
 np.int64(45384),
 np.int64(45415),
 np.int64(45446),
 np.int64(45477),
 np.int64(45508),
 np.int64(45539),
 np.int64(45570),
 np.int64(45601),
 np.int64(45632),
 np.int64(45663),
 np.int64(45694),
 np.int64(45725),
 np.int64(45756),
 np.int64(45787),
 np.int64(45818),
 np.int64(45849),
 np.int64(45880),
 np.int64(45911),
 np.int64(45942),
 np.int64(45973),
 np.int64(46004),
 np.int64(46035),
 np.int64(46066),
 np.int64(46097),
 np.int64(46128),
 np.int64(46159),
 np.int64(46190),
 np.int64(46221),
 np.int64(46252),
 np.int64(46283),
 np.int64(46314),
 np.int64(46345)}

In [264]:
suspicious_ids = [45322,45353,45384,45415,45446,45477,45508,45539,45570,45601,45632,45663,45694,45725,45756,45787,45818,45849,45880,45911,45942,45973,46004,46035,46066,46097,46128,46159,46190,46221,46252,46283,46314,46345]
combined_df[combined_df['player_id'].isin(suspicious_ids)][['player_id','year','team','games_played','kicks']]

       player_id  year                       team  games_played  kicks
8335       45508  2007               Sydney Swans             1    2.0
12079      45725  1997              Carlton Blues            22  191.0
12881      45322  1998  North Melbourne Kangaroos            14   90.0
12882      45322  1999  North Melbourne Kangaroos            10   27.0
12883      45322  2000  North Melbourne Kangaroos             3    9.0
...          ...   ...                        ...           ...    ...
24556      45570  2001             Hawthorn Hawks            17  188.0
24557      45570  2001             Hawthorn Hawks             3   28.0
24558      45570  2002             Hawthorn Hawks            11   81.0
24559      45570  2003             Hawthorn Hawks             5   27.0
24560      45570  2004              Carlton Blues             9   43.0

[253 rows x 5 columns]

### Exporting and Downloading the Dataset

I will now save the `combined_df` to a CSV file and download it.

In [266]:
combined_df.to_csv('afl_combined_cleaned_data.csv', index=False)