In [ ]:

import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('operations.csv')

/tmp/ipykernel_647/1621001728.py:1: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('operations.csv')

In [ ]:
df

,Mission ID,Mission Date,Theater of Operations,Country,Air Force,Unit ID,Aircraft Series,Callsign,Mission Type,Takeoff Base,...,Incendiary Devices Weight (Tons),Fragmentation Devices,Fragmentation Devices Type,Fragmentation Devices Weight (Pounds),Fragmentation Devices Weight (Tons),Total Weight (Pounds),Total Weight (Tons),Time Over Target,Bomb Damage Assessment,Source ID
0,1,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN
1,2,8/15/1943,PTO,USA,5 AF,400 BS,B24,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,9366.0
2,3,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
3,4,8/15/1943,MTO,USA,12 AF,27 FBG/86 FBG,A36,NaN,NaN,PONTE OLIVO AIRFIELD,...,NaN,NaN,NaN,NaN,NaN,NaN,7.5,NaN,NaN,NaN
4,5,8/15/1943,PTO,USA,5 AF,321 BS,B24,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,22585.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178276,178738,2/16/1945,CBI,USA,10 AF,89 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,35815.0
178277,178739,2/16/1945,CBI,USA,10 AF,90 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,35020.0
178278,178740,2/16/1945,CBI,USA,10 AF,90 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,35022.0
178279,178741,2/16/1945,PTO,NEW ZEALAND,RNZAF,NO. 22 SQUADRON RNZAF,F4U,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8000.0,4.0,NaN,NaN,NaN
178280,178742,2/16/1945,CBI,USA,10 AF,59 FS,P47,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,33784.0

In [ ]:
df.isnull().sum()

Mission ID                                    0
Mission Date                                  0
Theater of Operations                      3158
Country                                   51787
Air Force                                 51837
Unit ID                                  127368
Aircraft Series                             116
Callsign                                 178260
Mission Type                             131095
Takeoff Base                             174898
Takeoff Location                         174943
Takeoff Latitude                         175300
Takeoff Longitude                        175301
Target ID                                 50875
Target Country                              599
Target City                                2263
Target Type                               31911
Target Industry                           51802
Target Priority                           43561
Target Latitude                            8716
Target Longitude                           8738
Altitude (Hundreds of Feet)               57455
Airborne Aircraft                         96039
Attacking Aircraft                        53173
Bombing Aircraft                          96669
Aircraft Returned                        178148
Aircraft Failed                          178034
Aircraft Damaged                         178243
Aircraft Lost                            178123
High Explosives                          143544
High Explosives Type                     136336
High Explosives Weight (Pounds)          176260
High Explosives Weight (Tons)             32080
Incendiary Devices                       174998
Incendiary Devices Type                  172762
Incendiary Devices Weight (Pounds)       177925
Incendiary Devices Weight (Tons)         152549
Fragmentation Devices                    172513
Fragmentation Devices Type               172516
Fragmentation Devices Weight (Pounds)    178087
Fragmentation Devices Weight (Tons)      161379
Total Weight (Pounds)                    176162
Total Weight (Tons)                       11773
Time Over Target                         177592
Bomb Damage Assessment                   178177
Source ID                                  4045
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178281 entries, 0 to 178280
Data columns (total 46 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Mission ID                             178281 non-null  int64
 1   Mission Date                           178281 non-null  object
 2   Theater of Operations                  175123 non-null  object
 3   Country                                126494 non-null  object
 4   Air Force                              126444 non-null  object
 5   Unit ID                                50913 non-null   object
 6   Aircraft Series                        178165 non-null  object
 7   Callsign                               21 non-null      object
 8   Mission Type                           47186 non-null   object
 9   Takeoff Base                           3383 non-null    object
 10  Takeoff Location                       3338 non-null    object
 11  Takeoff Latitude                       2981 non-null    object
 12  Takeoff Longitude                      2980 non-null    float64
 13  Target ID                              127406 non-null  object
 14  Target Country                         177682 non-null  object
 15  Target City                            176018 non-null  object
 16  Target Type                            146370 non-null  object
 17  Target Industry                        126479 non-null  object
 18  Target Priority                        134720 non-null  object
 19  Target Latitude                        169565 non-null  float64
 20  Target Longitude                       169543 non-null  float64
 21  Altitude (Hundreds of Feet)            120826 non-null  float64
 22  Airborne Aircraft                      82242 non-null   float64
 23  Attacking Aircraft                     125108 non-null  float64
 24  Bombing Aircraft                       81612 non-null   float64
 25  Aircraft Returned                      133 non-null     float64
 26  Aircraft Failed                        247 non-null     float64
 27  Aircraft Damaged                       38 non-null      float64
 28  Aircraft Lost                          158 non-null     float64
 29  High Explosives                        34737 non-null   float64
 30  High Explosives Type                   41945 non-null   object
 31  High Explosives Weight (Pounds)        2021 non-null    object
 32  High Explosives Weight (Tons)          146201 non-null  float64
 33  Incendiary Devices                     3283 non-null    float64
 34  Incendiary Devices Type                5519 non-null    object
 35  Incendiary Devices Weight (Pounds)     356 non-null     float64
 36  Incendiary Devices Weight (Tons)       25732 non-null   float64
 37  Fragmentation Devices                  5768 non-null    float64
 38  Fragmentation Devices Type             5765 non-null    object
 39  Fragmentation Devices Weight (Pounds)  194 non-null     float64
 40  Fragmentation Devices Weight (Tons)    16902 non-null   float64
 41  Total Weight (Pounds)                  2119 non-null    float64
 42  Total Weight (Tons)                    166508 non-null  float64
 43  Time Over Target                       689 non-null     object
 44  Bomb Damage Assessment                 104 non-null     object
 45  Source ID                              174236 non-null  float64
dtypes: float64(22), int64(1), object(23)
memory usage: 62.6+ MB

In [ ]:
df.describe()

,Mission ID,Takeoff Longitude,Target Latitude,Target Longitude,Altitude (Hundreds of Feet),Airborne Aircraft,Attacking Aircraft,Bombing Aircraft,Aircraft Returned,Aircraft Failed,...,High Explosives Weight (Tons),Incendiary Devices,Incendiary Devices Weight (Pounds),Incendiary Devices Weight (Tons),Fragmentation Devices,Fragmentation Devices Weight (Pounds),Fragmentation Devices Weight (Tons),Total Weight (Pounds),Total Weight (Tons),Source ID
count,178281.000000,2980.000000,169565.000000,169543.000000,120826.000000,82242.000000,125108.000000,81612.000000,133.000000,247.000000,...,146201.000000,3283.000000,356.000000,25732.000000,5768.000000,194.000000,16902.000000,2.119000e+03,166508.000000,174236.000000
mean,89414.547041,220.618627,38.067793,43.340213,139.026812,12.329771,10.218899,12.347486,2.157895,4.275304,...,23.911995,132.001965,19962.732022,21.527213,102.684560,2065.630928,12.017136,1.237718e+04,25.760326,152670.902322
std,51649.744549,454.046956,18.711405,59.681160,186.818278,12.514833,11.246399,12.573549,1.369816,5.924758,...,90.092020,498.596761,45331.714255,66.692639,158.941650,2424.138566,27.221410,2.064155e+05,90.643876,105544.795936
min,1.000000,-177.328611,-37.416667,-179.451285,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,1.000000
25%,44571.000000,14.400000,26.250000,7.620000,70.000000,2.000000,2.000000,2.000000,1.000000,1.000000,...,2.000000,7.000000,218.750000,1.000000,10.000000,598.400000,1.000000,2.100000e+03,2.000000,53476.500000
50%,89540.000000,29.851389,47.500000,11.330000,122.000000,11.000000,7.000000,11.000000,2.000000,2.000000,...,9.000000,14.000000,2640.000000,6.000000,38.461538,1500.000000,3.000000,5.200000e+03,9.290000,167604.500000
75%,134171.000000,96.133222,50.930000,97.400000,223.000000,17.000000,12.000000,18.000000,3.000000,4.000000,...,30.000000,32.000000,12500.000000,18.000000,133.333333,2400.000000,12.000000,1.080000e+04,31.000000,211284.250000
max,178742.000000,1355.000000,1108.000000,1000.650000,40000.000000,332.000000,332.000000,332.000000,7.000000,48.000000,...,20000.000000,4875.000000,420000.000000,999.000000,3000.000000,20640.000000,900.000000,9.500000e+06,20000.000000,699625.000000

In [ ]:
df.columns

Index(['Mission ID', 'Mission Date', 'Theater of Operations', 'Country',
       'Air Force', 'Unit ID', 'Aircraft Series', 'Callsign', 'Mission Type',
       'Takeoff Base', 'Takeoff Location', 'Takeoff Latitude',
       'Takeoff Longitude', 'Target ID', 'Target Country', 'Target City',
       'Target Type', 'Target Industry', 'Target Priority', 'Target Latitude',
       'Target Longitude', 'Altitude (Hundreds of Feet)', 'Airborne Aircraft',
       'Attacking Aircraft', 'Bombing Aircraft', 'Aircraft Returned',
       'Aircraft Failed', 'Aircraft Damaged', 'Aircraft Lost',
       'High Explosives', 'High Explosives Type',
       'High Explosives Weight (Pounds)', 'High Explosives Weight (Tons)',
       'Incendiary Devices', 'Incendiary Devices Type',
       'Incendiary Devices Weight (Pounds)',
       'Incendiary Devices Weight (Tons)', 'Fragmentation Devices',
       'Fragmentation Devices Type', 'Fragmentation Devices Weight (Pounds)',
       'Fragmentation Devices Weight (Tons)', 'Total Weight (Pounds)',
       'Total Weight (Tons)', 'Time Over Target', 'Bomb Damage Assessment',
       'Source ID'],
      dtype='object')

In [ ]:
display(df.Country)

0                 USA
1                 USA
2                 USA
3                 USA
4                 USA
             ...
178276            USA
178277            USA
178278            USA
178279    NEW ZEALAND
178280            USA
Name: Country, Length: 178281, dtype: object

In [ ]:
missing = df.isna().sum().sort_values(ascending=False)
missing[missing > 0].head(20)

Callsign                                 178260
Aircraft Damaged                         178243
Bomb Damage Assessment                   178177
Aircraft Returned                        178148
Aircraft Lost                            178123
Fragmentation Devices Weight (Pounds)    178087
Aircraft Failed                          178034
Incendiary Devices Weight (Pounds)       177925
Time Over Target                         177592
High Explosives Weight (Pounds)          176260
Total Weight (Pounds)                    176162
Takeoff Longitude                        175301
Takeoff Latitude                         175300
Incendiary Devices                       174998
Takeoff Location                         174943
Takeoff Base                             174898
Incendiary Devices Type                  172762
Fragmentation Devices Type               172516
Fragmentation Devices                    172513
Fragmentation Devices Weight (Tons)      161379
dtype: int64

**Checked missing values:**
all columns were checked so that it can be determined which to keep, which to drop and which to fix

In [ ]:

cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(include=['float64', 'int64']).columns


df[cat_cols] = df[cat_cols].fillna('UNKNOWN')
df[num_cols] = df[num_cols].fillna(0)

Filling up the null values and fixing datatypes in next cell

Because:
- Most missing values here are **structurally missing, not errors**. For example, (Incendiary Devices) is blank
  when a mission didn't drop incendiary bombs, so it makes sense to fill **numeric columns with 0**.
- Text columns like (Aircraft Series) or (Target Type) are filled with ("UNKNOWN") instead of dropping,
  since dropping would throw away a huge portion of the dataset.
- Rows where the **Mission Date** itself is missing/unparsable are dropped, since date is essential for analysis
  and can't be reasonably guessed.

In [ ]:

df['Mission Date'] = pd.to_datetime(df['Mission Date'], errors='coerce')

numeric_like_cols = ['Takeoff Latitude', 'High Explosives Weight (Pounds)', 'Time Over Target']
for col in numeric_like_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

df = df.dropna(subset=['Mission Date'])

df.dtypes[['Mission Date', 'Takeoff Latitude', 'High Explosives Weight (Pounds)']]

Mission Date                       datetime64[ns]
Takeoff Latitude                          float64
High Explosives Weight (Pounds)           float64
dtype: object

**Fixed wrong Datatypes**

In [ ]:
df = df.drop_duplicates()

**Removed all duplicate rows from the dataset**

In [ ]:
df['Mission Year'] = df['Mission Date'].dt.year

df['Bombing Success Rate'] = df.apply(lambda row: row['Bombing Aircraft'] / row['Airborne Aircraft'] if row['Airborne Aircraft'] > 0 else 0,axis=1)

df[['Mission Date', 'Mission Year', 'Airborne Aircraft', 'Bombing Aircraft', 'Bombing Success Rate']].head()

,Mission Date,Mission Year,Airborne Aircraft,Bombing Aircraft,Bombing Success Rate
0,1943-08-15,1943,20.0,20.0,1.0
1,1943-08-15,1943,0.0,0.0,0.0
2,1943-08-15,1943,18.0,36.0,2.0
3,1943-08-15,1943,15.0,15.0,1.0
4,1943-08-15,1943,0.0,0.0,0.0

**Created 2 Derived Columns**

- **Mission Year** is extracted from **Mission Date** using a vectorized **.dt** operation.
- **Bombing Success Rate** is the fraction of airborne aircraft that actually reached and bombed the target,
  calculated with **.apply()** since it needs conditional logic.

In [ ]:
summary = df.groupby(['Theater of Operations', 'Mission Year']).agg(Total_Missions=('Mission ID', 'count'),Total_Bomb_Weight_Tons=('Total Weight (Tons)', 'sum')).reset_index()
summary.head(10)

  Theater of Operations  Mission Year  Total_Missions  Total_Bomb_Weight_Tons
0                   CBI          1942             449                977.2981
1                   CBI          1943            1585               7918.6804
2                   CBI          1944            6580              21874.8250
3                   CBI          1945            3790              16493.2515
4           EAST AFRICA          1940              15               4776.0000
5           EAST AFRICA          1941              21                  4.3800
6           EAST AFRICA          1942              70                 62.5000
7           EAST AFRICA          1943              29               1179.7000
8           EAST AFRICA          1944               7                417.0000
9                   ETO          1939              41                  0.0000

**Reshaped Data with groupby() + .agg()**

summarized the data by **Theater of Operations** and **Mission Year**, showing total missions flown
and total bomb weight dropped (in tons), turning 178k raw rows into a compact summary table.

In [ ]:
theater_lookup = pd.DataFrame({
    'Theater of Operations': ['ETO', 'PTO', 'MTO', 'CBI', 'EAST AFRICA', 'MADAGASCAR'],
    'Theater Full Name': [
        'European Theater of Operations',
        'Pacific Theater of Operations',
        'Mediterranean Theater of Operations',
        'China-Burma-India Theater',
        'East Africa Theater',
        'Madagascar Theater'
    ]
})

final_summary = summary.merge(theater_lookup, on='Theater of Operations', how='left')
final_summary
final_summary.head(11)

,Theater of Operations,Mission Year,Total_Missions,Total_Bomb_Weight_Tons,Theater Full Name
0,CBI,1942,449,977.2981,China-Burma-India Theater
1,CBI,1943,1585,7918.6804,China-Burma-India Theater
2,CBI,1944,6580,21874.8250,China-Burma-India Theater
3,CBI,1945,3790,16493.2515,China-Burma-India Theater
4,EAST AFRICA,1940,15,4776.0000,East Africa Theater
5,EAST AFRICA,1941,21,4.3800,East Africa Theater
6,EAST AFRICA,1942,70,62.5000,East Africa Theater
7,EAST AFRICA,1943,29,1179.7000,East Africa Theater
8,EAST AFRICA,1944,7,417.0000,East Africa Theater
9,ETO,1939,41,0.0000,European Theater of Operations
10,ETO,1940,6527,10043.0000,European Theater of Operations

Merged with manually created dataframe, **theater of mission** was not clear, they were all short forms, so made another column named **theater full name**